version: 2.1
orbs:
  elixir: membraneframework/elixir@1

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters: &filters
            tags:
              only: /v.*/
        steps:
          - checkout
          - run: | 
            mix deps.get
            mix deps.compile
            export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:./agora_sdk
            mix compile --force --warnings-as-errors