version: 2.1
orbs:
  elixir: membraneframework/elixir@1

jobs:
  get_agora:
    steps: 
      - run: chmod a+x install.sh
      - run: ./install
      - run: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:./agora_sdk

workflows:
  version: 2
  build:
    jobs:
      - elixir/build_test:
          filters: &filters
            tags:
              only: /v.*/
          requires:
            - get_agora
      - elixir/test:
          filters:
            <<: *filters
          requires:
            - get_agora
      - elixir/lint:
          filters:
            <<: *filters
      # - elixir/hex_publish:
      #     requires:
      #       - elixir/build_test
      #       - elixir/test
      #       - elixir/lint
      #     context:
      #       - Deployment
      #     filters:
      #       branches:
      #         ignore: /.*/
      #       tags:
      #         only: /v.*/
