version: 2.1
orbs:
  elixir: membraneframework/elixir@1.2

workflows:
  version: 2
  build:
    jobs:
      - elixir/build_test
      - elixir/test
      - elixir/lint

  publish:
    jobs:
      - elixir/build_test:
          filters: &filters-publish  # this yaml anchor allows for reusing this filter set elsewhere
            branches:
              ignore: /.*/
            tags:
              only: /v.*/
      - elixir/test:
          filters:
            <<: *filters-publish  # calling the anchor
      - elixir/lint:
          filters:
            <<: *filters-publish
      - elixir/hex_publish:
          requires:
            - elixir/build_test
            - elixir/test
            - elixir/lint
          context:
            - Deployment
          filters:
            <<: *filters-publish
