version: 2.1
orbs:
  elixir: membraneframework/elixir@1

workflows:
  version: 2
  build:
    jobs:
      - elixir/build_test:
          filters: &filters
            tags:
              only: /v.*/
          pre-steps:
            - checkout
            - run: chmod a+x install.sh
            - run: ./install.sh
            - run: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:./agora_sdk
      - elixir/lint:
          filters:
            <<: *filters
          pre-steps:
            - checkout
            - run: chmod a+x install.sh
            - run: ./install.sh
            - run: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:./agora_sdk